defaults:
  - base_model

model_type: satmae
out_features: true
task: classification
freeze_backbone: true
embed_dim: 1024
image_resolution: 224
patch_size: 16
num_channels: 3
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/checkpoint_ViT-L_pretrain_fmow_rgb.pth
full_finetune: False
trainable_params:
  - patch_embed.proj.weight
  - patch_embed.proj.bias

