defaults:
  - base_model_senpamae

model_type: senpamae
num_channels: 3
embed_dim: 768
image_size: 144
task: classification
full_finetune: false
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/basemae.pt