defaults:
  - base_model

model_type: softcon
softcon_size: vit_small
embed_dim: 384
task: segmentation
image_resolution: 224
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/B13_vits14_softcon.pth
num_channels: 13
